---
title: So... How did we end up here?
author: Marie Christine Dussault
date: '2018-02-04'
slug: so-how-did-we-end-up-here
categories:
  - introduction
tags:
  - introduction
---

Really, how did the person who hates writing end up writing a blog? A lot of encouragement (thanks, [**Maëlle**](http://www.masalmon.eu/)!) and a genuine desire to finally start working on the personal development that becomes important when you realise a postdoc is a terminal affliction.

The main motivation for starting to blog is to document my journey learning how to use the statistical computing language R. Somehow, along the way, I've fallen for the intricacies, quirks, and little wins that I've achieved in my three months of intense R study. However, the real seed of R goes as far back as 2012, when I attended an R introduction at University College London with my flatmate at the time. We wanted to look at using R in our PhD's but in the end, I chickened out and didn't look back...

Until 2015. 

After my PhD, I moved to South Africa to take up a postdoc and work with a group of physical anthropologists who are R users due to the influence of a couple of our colleagues. I did a workshop on R in anthropology that first year, and while I discovered that I wanted to focus on research involving a lot more statistics, I still didn't fully adopt R. I published a paper in 2016 and fell back into the old habit of SPSS (which shall never be mentioned again).

Come 2017, I spent some time with one our R loving colleagues and decided to commit myself fully at that point. I had started an entirely new project, outside my current sub-speciality of anthropology, and it came with the prospect of so much interesting data that I felt the need to go all in to be able to use the tools I wanted to. My colleague kindly shared resources with me and I started to learn R intensively using anthropological data. I found that this helped immensely, allowing to frame the learning within a context that I knew already. After going through all the resources, I searched to expand my skills. I already had a solid background in statistics (I now teach statistics in anthropology), having spent many years nerding out on the actual theory and inner workings of statistics (not sure why!), so what I needed was to dive deep into R and never come back...

I searched through the (**terrifying**) amount of online courses where I thought I might be able to learn R. I went through a large chunk of Johns Hopkins coursera course, read parts of books, and tried different approaches. I contemplated over and over spending the money (which was a rather large amount on an African postdoc stipend) for [**Datacamp**](https://www.datacamp.com/). A sale came up around American Thanksgiving and I finally decided I could justify the expense. 

_Best. Decision. Ever._

I've discovered that my style of learning really involves something I wasn't getting via other learning modes and that is the practical experience that Datacamp has built in to their courses. The five to ten minute videos followed by numerous coding examples for the learner to complete is brilliant and I don't think I would be where I am, so quickly, without it.

I've finally fully bought in to the R world and I don't regret it. I want to continue learning R on a daily basis. I want to start working on little projects alongside my 5 big work projects, so that I can sharpen my skills and continue to work on finding new ways to approach data that can translate to physical anthropology. I know I can achieve this with the help of the awesome R community that I've forced myself to become involved in (introverts, unite!). But mostly, I want to get to a point where I can help to guide another beginner into the wonderful world of R.

And that, whoever you are, is how we ended up here...



